const fs=require('fs');
const s=fs.readFileSync('index.html','utf8');
let n=0; const has=(x,m)=>{if(!s.includes(x)){console.error('FAIL:',m);process.exitCode=1}else n++};
const lacks=(x,m)=>{if(s.includes(x)){console.error('FAIL:',m);process.exitCode=1}else n++};
has('const ISAGI={','Isagi constants');
has('visionMax:100, visionStart:15, visionPerSec:27','Vision 0-100, starts 15, cap 27/s');
has('basicDmg:12, basicCd:gs(2.8)','Controlled Shot nerf');
has('firstDmg:32, firstT:gs(2)','First-Touch Shot balance');
has('blindCd:gs(6.5), blindT:gs(1), blindMove:2.10, blindTake:.68','Blind Spot Run balance');
has('directDmg:62, directPerfect:80, directCd:gs(7.5)','Direct / Perfect Timing balance');
has('directCd:gs(7.5), directWind:gs(.45)','Direct Shot faster cast');
has('ultRange:500, ultWind:gs(.85)','Two-Gun Volley faster cast');
has('puzzleCd:gs(9.5), puzzleT:gs(.75), puzzleMove:.60, puzzleVision:26','Puzzle Pieces balance');
has('analyzedT:gs(5.5), analyzedBonus:6, analyzedBonusMax:2','Analyzed balance');
has('ultDmg:135, ultDevour:157, ultPierce:.15','Two-Gun Volley balance');
has('basicSpeed:BALL_SPD*1.02','basic football speed near Tsubasa');
has('directSpeed:BIC_SPD','Direct Shot speed matches Tsubasa overhead');
has('ultSpeed:BIC_SPD*1.03','ultimate only slightly faster than Tsubasa overhead');
has('function isagiShotSpread','shots have accuracy spread');
has("return (chance(.5)?1:-1)*rnd(min,max);",'shots can miss left or right');
lacks("p.kind==='controlled'&&p.target&&p.target.alive",'Controlled Shot no longer homes');
lacks("p.kind==='ult'&&!p.adjusted",'ultimate no longer retargets in flight');
has('ballShape(p.r,p.spin*(sp/300))','Isagi uses Tsubasa football rendering');
has("txt:'METAVISION'",'Metavision UI');
has("ctx.fillText('CRITICAL SPACE'",'Critical Space UI');
has('function isagiBestTarget','tactical target selection');
has('function isagiCriticalSpace','Critical Space calculation');
has('function isagiReadDodge','read dodge');
has('kind===\'ult\'||kind===\'domain\'||kind===\'dot\'','no ultimate/AOE auto dodge');
has('f.isagiShot=null; f.isagiBallReturn=ISAGI.ballReturn','one ball return system');
has('f.isagiVisionLock=ISAGI.visionLock','post-ultimate Vision lock');
has("role:'ranged', want:225",'roster entry');
has("isagi:{ role:{vi:'Tactical Finisher · Adaptive Striker'",'DEX entry');
lacks('isagiLowHp','no low-HP power mechanic');
if(!process.exitCode)console.log(`Isagi contract OK (${n} checks)`);
