const fs=require('fs');
const s=fs.readFileSync('index.html','utf8');
let n=0; const has=(x,m)=>{if(!s.includes(x)){console.error('FAIL:',m);process.exitCode=1}else n++};
const lacks=(x,m)=>{if(s.includes(x)){console.error('FAIL:',m);process.exitCode=1}else n++};
has('const ISAGI={','Isagi constants');
has('visionMax:100, visionStart:15, visionPerSec:30','Vision 0-100, starts 15, cap 30/s');
has('basicDmg:14, basicCd:gs(1.1)','Controlled Shot');
has('firstDmg:38, firstT:gs(2)','First-Touch Shot');
has('blindCd:gs(6), blindT:gs(1), blindMove:2.20, blindTake:.60','Blind Spot Run');
has('directDmg:72, directPerfect:96, directCd:gs(7)','Direct / Perfect Timing');
has('puzzleCd:gs(9), puzzleT:gs(1), puzzleMove:.60, puzzleVision:30','Puzzle Pieces');
has('analyzedT:gs(6), analyzedBonus:8, analyzedBonusMax:2','Analyzed');
has('ultDmg:160, ultDevour:190, ultPierce:.20','Two-Gun Volley');
has("txt:'METAVISION'",'Metavision UI');
has("ctx.fillText('CRITICAL SPACE'",'Critical Space UI');
has('function isagiBestTarget','tactical target selection');
has('function isagiCriticalSpace','Critical Space calculation');
has('function isagiReadDodge','read dodge');
has('kind===\'ult\'||kind===\'domain\'||kind===\'dot\'','no ultimate/AOE auto dodge');
has('f.isagiShot=null; f.isagiBallReturn=ISAGI.ballReturn','one ball return system');
has('f.isagiVisionLock=ISAGI.visionLock','post-ultimate Vision lock');
has("role:'ranged', want:225",'roster entry');
has("isagi:{ role:{vi:'Tactical Finisher · Adaptive Striker'",'DEX entry');
lacks('isagiLowHp','no low-HP power mechanic');
if(!process.exitCode)console.log(`Isagi contract OK (${n} checks)`);
