const fs=require('fs');
const s=fs.readFileSync('index.html','utf8');
let n=0; const has=(x,m)=>{if(!s.includes(x)){console.error('FAIL:',m);process.exitCode=1}else n++};
const lacks=(x,m)=>{if(s.includes(x)){console.error('FAIL:',m);process.exitCode=1}else n++};
has('const ISAGI={','Isagi constants');
has('visionMax:100, visionStart:15, visionPerSec:30','Vision 0-100, starts 15, cap 30/s');
has('basicDmg:12, basicCd:gs(2.8)','Controlled Shot nerf');
has('firstDmg:34, firstT:gs(2)','First-Touch Shot nerf');
has('blindCd:gs(6), blindT:gs(1), blindMove:2.20, blindTake:.60','Blind Spot Run');
has('directDmg:66, directPerfect:86, directCd:gs(7)','Direct / Perfect Timing nerf');
has('puzzleCd:gs(9), puzzleT:gs(1), puzzleMove:.60, puzzleVision:30','Puzzle Pieces');
has('analyzedT:gs(6), analyzedBonus:8, analyzedBonusMax:2','Analyzed');
has('ultDmg:145, ultDevour:170, ultPierce:.20','Two-Gun Volley nerf');
has('basicSpeed:BALL_SPD*1.02','basic football speed near Tsubasa');
has('directSpeed:BIC_SPD','Direct Shot speed matches Tsubasa overhead');
has('ultSpeed:BIC_SPD*1.03','ultimate only slightly faster than Tsubasa overhead');
has('function isagiShotSpread','shots have accuracy spread');
has("return (chance(.5)?1:-1)*rnd(min,max);",'shots can miss left or right');
lacks("p.kind==='controlled'&&p.target&&p.target.alive",'Controlled Shot no longer homes');
lacks("p.kind==='ult'&&!p.adjusted",'ultimate no longer retargets in flight');
has('ballShape(p.r,p.spin*(sp/300))','Isagi uses Tsubasa football rendering');
has("txt:'METAVISION'",'Metavision UI');
has("ctx.fillText('CRITICAL SPACE'",'Critical Space UI');
has('function isagiBestTarget','tactical target selection');
has('function isagiCriticalSpace','Critical Space calculation');
has('function isagiReadDodge','read dodge');
has('kind===\'ult\'||kind===\'domain\'||kind===\'dot\'','no ultimate/AOE auto dodge');
has('f.isagiShot=null; f.isagiBallReturn=ISAGI.ballReturn','one ball return system');
has('f.isagiVisionLock=ISAGI.visionLock','post-ultimate Vision lock');
has("role:'ranged', want:225",'roster entry');
has("isagi:{ role:{vi:'Tactical Finisher · Adaptive Striker'",'DEX entry');
lacks('isagiLowHp','no low-HP power mechanic');
if(!process.exitCode)console.log(`Isagi contract OK (${n} checks)`);
